import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { savePage } from "@/features/content/cms-actions";
import { createClient } from "@/lib/supabase/server";

export default async function AdminPagesPage() {
  const supabase = await createClient();
  const { data } = await supabase.from("pages").select("id, name, slug, status, meta_description, updated_at").order("name");
  return <><header className="admin-page-header"><div><span>Structured content</span><h1>Pages</h1><p>Manage page metadata and the controlled sections used by the public website.</p></div></header><section className="admin-panel"><div className="admin-table-wrap"><table><thead><tr><th>Page</th><th>Status</th><th>SEO description</th><th>Updated</th><th /></tr></thead><tbody>{data?.map((page) => <tr key={page.id}><td><strong>{page.name}</strong><small>/{page.slug === "home" ? "" : page.slug}</small></td><td><span className={`status-pill ${page.status}`}>{page.status}</span></td><td>{page.meta_description ? "Complete" : "Missing"}</td><td>{new Intl.DateTimeFormat("en-ZW", { dateStyle: "medium" }).format(new Date(page.updated_at))}</td><td><Link href={`/admin/pages/${page.id}`}>Edit <ArrowUpRight size={14} /></Link></td></tr>)}</tbody></table></div></section><section className="editor-panel compact-create"><div className="editor-panel-title"><h2>Create a page</h2><p>New pages start as drafts unless explicitly published.</p></div><form className="editor-fields" action={savePage}><label><span>Name</span><input name="name" required /></label><label><span>Slug</span><input name="slug" required /></label><input type="hidden" name="metaTitle" value="" /><input type="hidden" name="metaDescription" value="" /><input type="hidden" name="canonicalUrl" value="" /><input type="hidden" name="intent" value="draft" /><label className="checkbox-field"><input name="robotsIndex" type="checkbox" defaultChecked /><span>Allow indexing when published</span></label><button className="button button-primary">Create draft</button></form></section></>;
}
