import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

export const metadata: Metadata = { title: "About", description: "Meet Infinity Aura Technologies, a Zimbabwean technology company building useful, reliable digital systems." };

export default function AboutPage() {
  return <><section className="page-hero"><div className="container narrow"><span className="section-label">About Infinity Aura</span><h1>Technology should make people and organizations more capable.</h1><p>We are a Zimbabwean software and digital solutions company focused on thoughtful products, dependable engineering, and meaningful business outcomes.</p></div></section><section className="section"><div className="container story-grid"><div><span className="section-label">Our approach</span><h2>Understand first. Build with intention.</h2></div><div className="prose-copy"><p>Infinity Aura Technologies helps organizations turn ambitious ideas into digital products they can use, maintain, and grow. We begin by understanding the operating reality, the people involved, and the outcome that matters.</p><p>That perspective guides every technical choice. We value clarity over novelty, durable foundations over unnecessary complexity, and honest partnership throughout delivery.</p></div></div></section><section className="section section-soft"><div className="container principles-grid"><article><span>Mission</span><h2>Transform ideas into technology that empowers organizations.</h2></article><article><span>Vision</span><h2>Become a leading African technology company recognized for innovation, excellence, and impact.</h2></article></div></section><section className="section"><div className="container simple-cta"><div><span className="section-label">Work with us</span><h2>Bring us the challenge.</h2><p>We will help turn it into a clear and practical digital plan.</p></div><Link className="button button-primary" href="/contact">Start a conversation <ArrowRight size={17} /></Link></div></section></>;
}
