import type { ServiceRow, SolutionRow } from "@/types/database";

type EditorRecord = Partial<ServiceRow & SolutionRow>;

export function ContentEditor({ kind, record, action }: { kind: "service" | "solution"; record?: EditorRecord; action: (formData: FormData) => void | Promise<void> }) {
  const benefits = Array.isArray(record?.benefits) ? record.benefits.filter((item) => typeof item === "string").join("\n") : "";
  return (
    <form className="editor-form" action={action}>
      {record?.id && <input type="hidden" name="id" value={record.id} />}
      <section className="editor-panel"><div className="editor-panel-title"><h2>Core content</h2><p>Write for people first. Search metadata is managed below.</p></div><div className="editor-fields"><label className="field-wide"><span>Title</span><input name="title" defaultValue={record?.title ?? ""} minLength={2} maxLength={120} required /></label><label><span>URL slug</span><input name="slug" defaultValue={record?.slug ?? ""} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label>{kind === "service" ? <label><span>Icon key</span><select name="iconKey" defaultValue={record?.icon_key ?? "code-2"}><option value="code-2">Code</option><option value="panels-top-left">Web platform</option><option value="smartphone">Mobile</option><option value="graduation-cap">Education</option><option value="workflow">Automation</option><option value="brain-circuit">AI</option><option value="cloud">Cloud</option><option value="compass">Consulting</option></select></label> : <label><span>Category</span><input name="category" defaultValue={record?.category ?? ""} /></label>}<label className="field-wide"><span>Summary</span><textarea name="summary" rows={3} defaultValue={record?.summary ?? ""} minLength={10} maxLength={300} required /></label><label className="field-wide"><span>Detailed content</span><textarea name="body" rows={9} defaultValue={record?.body ?? ""} minLength={20} required /></label>{kind === "solution" && <label className="field-wide"><span>Benefits, one per line</span><textarea name="benefits" rows={5} defaultValue={benefits} /></label>}</div></section><aside className="editor-panel editor-publish"><div className="editor-panel-title"><h2>Publication</h2><p>Save privately or make this visible now.</p></div><div className="editor-fields"><label><span>Display order</span><input name="sortOrder" type="number" min={0} defaultValue={record?.sort_order ?? 100} required /></label><label className="checkbox-field"><input name="featured" type="checkbox" defaultChecked={record?.is_featured ?? false} /><span>Feature this item</span></label><button className="button button-secondary" name="intent" value="draft" type="submit">Save draft</button><button className="button button-primary" name="intent" value="published" type="submit">Publish now</button>{record?.status && <small>Current status: <span className={`status-pill ${record.status}`}>{record.status}</span></small>}</div></aside>
    </form>
  );
}
