import { Save, Trash2 } from "lucide-react";
import { ConfirmSubmitButton } from "@/components/admin/confirm-submit-button";
import { deletePageSection, savePageSection } from "@/features/content/cms-actions";
import type { PageSectionRow } from "@/types/database";

const sectionTypes = ["hero", "rich_text", "purpose", "services", "statistics", "solutions", "technologies", "testimonials", "contact", "cta"] as const;

export function PageSectionEditor({ pageId, section }: { pageId: string; section?: PageSectionRow }) {
  return <article className="editor-panel section-editor"><div className="editor-panel-title"><div><h2>{section?.section_key ?? "New section"}</h2><p>{section ? `${section.section_type} · order ${section.sort_order}` : "Add a controlled content section"}</p></div>{section && <form action={deletePageSection}><input type="hidden" name="id" value={section.id} /><input type="hidden" name="pageId" value={pageId} /><ConfirmSubmitButton className="icon-button danger" label={`Delete ${section.section_key}`}><Trash2 size={16} /></ConfirmSubmitButton></form>}</div><form action={savePageSection} className="editor-fields"><input type="hidden" name="pageId" value={pageId} />{section && <input type="hidden" name="id" value={section.id} />}<label><span>Section key</span><input name="sectionKey" defaultValue={section?.section_key ?? ""} required /></label><label><span>Type</span><select name="sectionType" defaultValue={section?.section_type ?? "rich_text"}>{sectionTypes.map((type) => <option key={type} value={type}>{type.replace("_", " ")}</option>)}</select></label><label className="field-wide"><span>Eyebrow</span><input name="eyebrow" defaultValue={section?.eyebrow ?? ""} /></label><label><span>Heading</span><input name="heading" defaultValue={section?.heading ?? ""} /></label><label><span>Accent text</span><input name="accentText" defaultValue={section?.accent_text ?? ""} /></label><label className="field-wide"><span>Body</span><textarea name="body" rows={4} defaultValue={section?.body ?? ""} /></label><label><span>Primary button label</span><input name="primaryLabel" defaultValue={section?.primary_cta_label ?? ""} /></label><label><span>Primary URL</span><input name="primaryUrl" defaultValue={section?.primary_cta_url ?? ""} /></label><label><span>Secondary button label</span><input name="secondaryLabel" defaultValue={section?.secondary_cta_label ?? ""} /></label><label><span>Secondary URL</span><input name="secondaryUrl" defaultValue={section?.secondary_cta_url ?? ""} /></label><label><span>Display order</span><input name="sortOrder" type="number" min={0} defaultValue={section?.sort_order ?? 100} required /></label><label className="checkbox-field"><input name="visible" type="checkbox" defaultChecked={section?.is_visible ?? true} /><span>Visible</span></label><button className="button button-secondary field-wide"><Save size={16} /> {section ? "Save section" : "Add section"}</button></form></article>;
}
