import Link from "next/link";
import { ArrowUpRight, FileText, Inbox, Lightbulb, MessageCircle, Plus } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function AdminDashboardPage() {
  const supabase = await createClient();
  const [publishedIdeas, draftIdeas, publishedServices, newLeads, activeLeads, visibleComments, recentIdeas, recentLeads] = await Promise.all([supabase.from("business_ideas").select("id", { count: "exact", head: true }).eq("status", "published"), supabase.from("business_ideas").select("id", { count: "exact", head: true }).eq("status", "draft"), supabase.from("services").select("id", { count: "exact", head: true }).eq("status", "published"), supabase.from("contact_enquiries").select("id", { count: "exact", head: true }).eq("status", "new"), supabase.from("contact_enquiries").select("id", { count: "exact", head: true }).in("status", ["new", "read", "in_progress"]), supabase.from("idea_comments").select("id", { count: "exact", head: true }).eq("status", "visible"), supabase.from("business_ideas").select("id,title,status,updated_at").order("updated_at", { ascending: false }).limit(5), supabase.from("contact_enquiries").select("id,reference_number,name,email,subject,status,created_at").order("created_at", { ascending: false }).limit(5)]);
  const metrics = [{ label: "Published ideas", value: publishedIdeas.count ?? 0, icon: Lightbulb }, { label: "Draft ideas", value: draftIdeas.count ?? 0, icon: FileText }, { label: "Community comments", value: visibleComments.count ?? 0, icon: MessageCircle }, { label: "Published services", value: publishedServices.count ?? 0, icon: FileText }, { label: "New leads", value: newLeads.count ?? 0, icon: Inbox }, { label: "Active leads", value: activeLeads.count ?? 0, icon: Inbox }];
  return <><header className="admin-page-header"><div><span>Overview</span><h1>What needs attention.</h1><p>A clear view of business ideas, community activity, and customer conversations.</p></div><div className="header-actions"><Link className="button button-primary" href="/admin/ideas/new"><Plus size={17} /> New idea</Link><Link className="button button-secondary" href="/admin/leads">Review leads</Link></div></header><section className="admin-metrics">{metrics.map(({ label, value, icon: Icon }) => <article key={label}><Icon size={18} /><strong>{value}</strong><p>{label}</p></article>)}</section><div className="admin-dashboard-grid"><section className="admin-panel"><div className="admin-panel-title"><div><h2>Recent ideas</h2><p>Latest publishing work.</p></div><Link href="/admin/ideas">View all <ArrowUpRight size={15} /></Link></div>{recentIdeas.data?.length ? <div className="simple-list">{recentIdeas.data.map((item) => <Link href={`/admin/ideas/${item.id}`} key={item.id}><span><strong>{item.title}</strong><small>{new Intl.DateTimeFormat("en-ZW", { dateStyle: "medium" }).format(new Date(item.updated_at))}</small></span><span className={`status-pill ${item.status}`}>{item.status}</span></Link>)}</div> : <div className="admin-empty">No ideas yet.</div>}</section><section className="admin-panel"><div className="admin-panel-title"><div><h2>Recent leads</h2><p>Latest website enquiries.</p></div><Link href="/admin/leads">View all <ArrowUpRight size={15} /></Link></div>{recentLeads.data?.length ? <div className="simple-list">{recentLeads.data.map((item) => <Link href={`/admin/leads/${item.id}`} key={item.id}><span><strong>{item.name}</strong><small>{item.subject ?? item.email}</small></span><span className={`status-pill ${item.status}`}>{item.status.replace("_", " ")}</span></Link>)}</div> : <div className="admin-empty">No leads yet.</div>}</section></div></>;
}
