import { notFound } from "next/navigation";
import { PageSectionEditor } from "@/components/admin/page-section-editor";
import { savePage } from "@/features/content/cms-actions";
import { createClient } from "@/lib/supabase/server";

export default async function AdminPageEditor({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient();
  const [page, sections] = await Promise.all([supabase.from("pages").select("*").eq("id", id).single(), supabase.from("page_sections").select("*").eq("page_id", id).order("sort_order")]);
  if (!page.data) notFound();
  return <><header className="admin-page-header"><div><span>Page editor</span><h1>{page.data.name}</h1><p>Page settings and ordered content sections.</p></div></header><form className="editor-form" action={savePage}><section className="editor-panel"><div className="editor-panel-title"><h2>Search and publication</h2><p>These fields describe the page to visitors and search engines.</p></div><div className="editor-fields"><input type="hidden" name="id" value={page.data.id} /><label><span>Name</span><input name="name" defaultValue={page.data.name} required /></label><label><span>Slug</span><input name="slug" defaultValue={page.data.slug} required /></label><label className="field-wide"><span>Meta title</span><input name="metaTitle" defaultValue={page.data.meta_title ?? ""} /></label><label className="field-wide"><span>Meta description</span><textarea name="metaDescription" rows={3} defaultValue={page.data.meta_description ?? ""} /></label><label className="field-wide"><span>Canonical URL</span><input name="canonicalUrl" defaultValue={page.data.canonical_url ?? ""} /></label><label className="checkbox-field"><input name="robotsIndex" type="checkbox" defaultChecked={page.data.robots_index} /><span>Allow search indexing</span></label></div></section><aside className="editor-panel editor-publish"><div className="editor-panel-title"><h2>Publication</h2><p>Choose the state to save.</p></div><div className="editor-fields"><button className="button button-secondary" name="intent" value="draft">Save draft</button><button className="button button-primary" name="intent" value="published">Publish</button><button className="button button-secondary" name="intent" value="archived">Archive</button></div></aside></form><div className="section-editor-list">{sections.data?.map((section) => <PageSectionEditor key={section.id} pageId={id} section={section} />)}<PageSectionEditor pageId={id} /></div></>;
}
